spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpaboard?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
         show_sql: true
         format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ;GaE3za?jrhkd/|rT9Y\$Gd\(^0qh)\D5^&?1W1k22p"-+L+wU<=\H;`8}a(CaCO